"use client";

import { useState, useEffect, useRef, useCallback, useContext } from "react";
import { Plus, Play, Pause, AlertCircle, RefreshCw, FileEdit, Trash2, X, Check, Upload, List } from "lucide-react";
import { SettingsContext } from "../phone-settings-app";
import type { VoiceApiConfig } from "@/lib/settings-types";
import { loadVoiceConfigs, saveVoiceConfigs } from "@/lib/settings-storage";
import { synthesizeSpeech } from "@/lib/tts-service";
import { ConfirmDialog } from "@/components/ui/modal";
import { Toggle, Input } from "@/components/ui/form";
import { Alert } from "@/components/ui/feedback";
import { INWORLD_TTS_MODELS, DEFAULT_INWORLD_TTS_MODEL, DEFAULT_INWORLD_BASE_URL } from "@/lib/inworld-tts";

const SUPPORTED_VOICE_PROVIDERS = new Set(["Minimax", "OpenAI", "ElevenLabs", "F5-TTS", "Inworld"]);
const MINIMAX_BASE_URL_OPTIONS = [{ id: "cn", label: "国内版", baseUrl: "https://api.minimaxi.com/v1" }, { id: "global", label: "海外版", baseUrl: "https://api.minimax.io/v1" }];
const DEFAULT_MINIMAX_BASE_URL = MINIMAX_BASE_URL_OPTIONS[0].baseUrl;
const GLOBAL_MINIMAX_BASE_URL = MINIMAX_BASE_URL_OPTIONS[1].baseUrl;
const MINIMAX_SPEED_MIN = 0.5, MINIMAX_SPEED_MAX = 2.0, MINIMAX_SPEED_STEP = 0.1, DEFAULT_SPEECH_SPEED = 1.0;
const MINIMAX_PITCH_MIN = -12, MINIMAX_PITCH_MAX = 12, MINIMAX_PITCH_STEP = 1, DEFAULT_SPEECH_PITCH = 0;
const ELEVENLABS_SPEED_MIN = 0.7, ELEVENLABS_SPEED_MAX = 1.2, ELEVENLABS_SPEED_STEP = 0.1;
const DEFAULT_ELEVENLABS_STABILITY = 0.5, DEFAULT_ELEVENLABS_SIMILARITY = 0.75, DEFAULT_ELEVENLABS_STYLE = 0, DEFAULT_ELEVENLABS_SPEAKER_BOOST = true;
const DEFAULT_ELEVENLABS_MODEL = "eleven_flash_v2_5", DEFAULT_F5_TTS_BASE_URL = "http://127.0.0.1:7861", DEFAULT_F5_TTS_MODEL = "F5TTS_v1_Base", DEFAULT_F5_TTS_NFE_STEP = 32;
const ELEVENLABS_MODELS = [{ id: "eleven_v3", name: "Eleven v3（表现力最强）" }, { id: "eleven_multilingual_v2", name: "Multilingual v2（高质量多语言）" }, { id: "eleven_flash_v2_5", name: "Flash v2.5（低延迟，推荐聊天）" }, { id: "eleven_turbo_v2_5", name: "Turbo v2.5（低延迟）" }];
const ELEVENLABS_LANGUAGE_OPTIONS = [{ value: "", label: "自动（不指定语言）" }, { value: "en", label: "English" }, { value: "zh", label: "中文" }, { value: "yue", label: "粤语" }, { value: "ja", label: "日本語" }, { value: "ko", label: "한국어" }, { value: "fr", label: "Français" }, { value: "de", label: "Deutsch" }, { value: "es", label: "Español" }, { value: "it", label: "Italiano" }, { value: "pt", label: "Português" }];
const VOICE_PROVIDER_OPTIONS = [{ value: "OpenAI", label: "OpenAI TTS" }, { value: "MinimaxCN", label: "Minimax 语音国内版" }, { value: "MinimaxGlobal", label: "Minimax 语音海外版" }, { value: "ElevenLabs", label: "ElevenLabs" }, { value: "Inworld", label: "Inworld AI" }, { value: "F5-TTS", label: "F5-TTS（本机）" }];
const DEFAULT_VOICE_CONFIGS: VoiceApiConfig[] = [{ id: "default-minimax-tts", name: "Minimax 语音", provider: "Minimax", apiKey: "", baseUrl: DEFAULT_MINIMAX_BASE_URL, model: "speech-2.8-turbo", defaultVoice: "male-qn-qingse", speechSpeed: DEFAULT_SPEECH_SPEED, speechPitch: DEFAULT_SPEECH_PITCH, enableSTT: true, enableTTS: true }];
const DEFAULT_MINIMAX_MODELS = [{ id: "speech-2.8-hd", name: "speech-2.8-hd" }, { id: "speech-2.8-turbo", name: "speech-2.8-turbo" }, { id: "speech-2.6-hd", name: "speech-2.6-hd" }, { id: "speech-2.6-turbo", name: "speech-2.6-turbo" }, { id: "speech-02-hd", name: "speech-02-hd" }, { id: "speech-02-turbo", name: "speech-02-turbo" }, { id: "speech-01-hd", name: "speech-01-hd" }, { id: "speech-01-turbo", name: "speech-01-turbo (速度快/性价比高)" }];
const MINIMAX_LANGUAGE_OPTIONS = [{ value: "", label: "不指定（保持默认）" }, { value: "auto", label: "自动识别" }, { value: "Chinese", label: "普通话" }, { value: "Chinese,Yue", label: "粤语" }, { value: "English", label: "英语" }, { value: "Arabic", label: "阿拉伯语" }, { value: "Russian", label: "俄语" }, { value: "Spanish", label: "西班牙语" }, { value: "French", label: "法语" }, { value: "Portuguese", label: "葡萄牙语" }, { value: "German", label: "德语" }, { value: "Turkish", label: "土耳其语" }, { value: "Dutch", label: "荷兰语" }, { value: "Ukrainian", label: "乌克兰语" }, { value: "Vietnamese", label: "越南语" }, { value: "Indonesian", label: "印尼语" }, { value: "Japanese", label: "日语" }, { value: "Italian", label: "意大利语" }, { value: "Korean", label: "韩语" }, { value: "Thai", label: "泰语" }, { value: "Polish", label: "波兰语" }, { value: "Romanian", label: "罗马尼亚语" }, { value: "Greek", label: "希腊语" }, { value: "Czech", label: "捷克语" }, { value: "Finnish", label: "芬兰语" }, { value: "Hindi", label: "印地语" }, { value: "Bulgarian", label: "保加利亚语" }, { value: "Danish", label: "丹麦语" }, { value: "Hebrew", label: "希伯来语" }, { value: "Malay", label: "马来语" }, { value: "Persian", label: "波斯语" }, { value: "Slovak", label: "斯洛伐克语" }, { value: "Swedish", label: "瑞典语" }, { value: "Croatian", label: "克罗地亚语" }, { value: "Filipino", label: "菲律宾语" }, { value: "Hungarian", label: "匈牙ri语" }, { value: "Norwegian", label: "挪威语" }, { value: "Slovenian", label: "斯洛文尼亚语" }, { value: "Catalan", label: "加泰罗尼亚语" }, { value: "Nynorsk", label: "新挪威语" }, { value: "Tamil", label: "泰米尔语" }, { value: "Afrikaans", label: "南非荷兰语" }];
const MINIMAX_PREVIEW_TEXT: Record<string,string> = { Chinese:"你好，很高兴认识你。这是一段普通话试听。", "Chinese,Yue":"大家好，我而家用紧粤语同你讲话，好开心认识你。", English:"Hello, it is nice to meet you. This is an English voice preview.", Japanese:"こんにちは、はじめまして。これは日本語の音声サンプルです。" };
const DEFAULT_MINIMAX_VOICES = [{ id:"male-qn-qingse", name:"青涩青年音 (male-qn-qingse)" }, { id:"female-shaonv", name:"少女音 (female-shaonv)" }, { id:"female-yujie", name:"御姐音 (female-yujie)" }, { id:"male-qn-badao", name:"霸道青年音 (male-qn-badao)" }, { id:"Wise_Woman", name:"知性女音 (Wise_Woman)" }, { id:"Friendly_Person", name:"亲切和蔼 (Friendly_Person)" }, { id:"Calm_Woman", name:"冷静女音 (Calm_Woman)" }, { id:"Cantonese_GentleLady", name:"粤语温柔女声 (Cantonese_GentleLady)" }, { id:"Cantonese_PlayfulMan", name:"粤语活泼男声 (Cantonese_PlayfulMan)" }, { id:"Cantonese_CuteGirl", name:"粤语可爱女孩 (Cantonese_CuteGirl)" }, { id:"Cantonese_KindWoman", name:"粤语善良女声 (Cantonese_KindWoman)" }];
const DEFAULT_OPENAI_VOICES = [{ id:"alloy",name:"Alloy" }, { id:"echo",name:"Echo" }, { id:"fable",name:"Fable" }, { id:"onyx",name:"Onyx" }, { id:"nova",name:"Nova" }, { id:"shimmer",name:"Shimmer" }];
type VoiceOption = { id:string; name:string; createdAt?:number };
const uniqueOptions = (options:VoiceOption[]) => { const seen=new Set<string>(); return options.filter(o=>{if(!o.id||seen.has(o.id))return false;seen.add(o.id);return true;}); };
const defaultVoiceOptions = (provider:string):VoiceOption[] => provider === "OpenAI" ? DEFAULT_OPENAI_VOICES : provider === "ElevenLabs" || provider === "F5-TTS" || provider === "Inworld" ? [] : DEFAULT_MINIMAX_VOICES;
const voiceOptionsForConfig = (config:VoiceApiConfig, fetched:Record<string,VoiceOption[]>) => uniqueOptions([...(fetched[config.id]||[]),...(config.customVoices||[]),...defaultVoiceOptions(config.provider)]);
const normalizeVoiceConfigs = (configs:VoiceApiConfig[]) => configs.filter(c=>SUPPORTED_VOICE_PROVIDERS.has(c.provider)).map(c=>c.provider!=="Minimax"?c:{...c,baseUrl:MINIMAX_BASE_URL_OPTIONS.some(o=>o.baseUrl===c.baseUrl)?c.baseUrl:DEFAULT_MINIMAX_BASE_URL,speechSpeed:typeof c.speechSpeed==="number"&&Number.isFinite(c.speechSpeed)?Math.min(MINIMAX_SPEED_MAX,Math.max(MINIMAX_SPEED_MIN,c.speechSpeed)):DEFAULT_SPEECH_SPEED,speechPitch:typeof c.speechPitch==="number"&&Number.isFinite(c.speechPitch)?Math.min(MINIMAX_PITCH_MAX,Math.max(MINIMAX_PITCH_MIN,Math.round(c.speechPitch))):DEFAULT_SPEECH_PITCH});
const makeCloneVoiceId=(c:VoiceApiConfig)=>`${((c.name||c.defaultVoice||"voice").toLowerCase().replace(/[^a-z0-9_-]+/g,"_").replace(/^_+|_+$/g,"").slice(0,24)||"voice")}_${Date.now().toString(36)}`.slice(0,64);
const providerSelectValue=(c:VoiceApiConfig)=>c.provider==="OpenAI"?"OpenAI":c.provider==="ElevenLabs"?"ElevenLabs":c.provider==="Inworld"?"Inworld":c.provider==="F5-TTS"?"F5-TTS":c.baseUrl===GLOBAL_MINIMAX_BASE_URL?"MinimaxGlobal":"MinimaxCN";

export function VoiceSettings(){
 const {setSubpageRightAction}=useContext(SettingsContext); const [configs,setConfigs]=useState<VoiceApiConfig[]>([]); const [editingId,setEditingId]=useState<string|null>(null); const [isNewConfig,setIsNewConfig]=useState(false); const [confirmDeleteId,setConfirmDeleteId]=useState<string|null>(null); const [playingVoiceId,setPlayingVoiceId]=useState<string|null>(null); const [cloneTargetId,setCloneTargetId]=useState<string|null>(null); const [cloneVoiceId,setCloneVoiceId]=useState(""); const [cloneFile,setCloneFile]=useState<File|null>(null); const [cloneError,setCloneError]=useState(""); const [isCloning,setIsCloning]=useState(false); const [manualModelIds,setManualModelIds]=useState<Record<string,boolean>>({}); const [manualVoiceIds,setManualVoiceIds]=useState<Record<string,boolean>>({}); const [isLoaded,setIsLoaded]=useState(false); const audioRef=useRef<HTMLAudioElement|null>(null); const [isFetching,setIsFetching]=useState<Record<string,boolean>>({}); const [fetchedVoices,setFetchedVoices]=useState<Record<string,VoiceOption[]>>({}); const [fetchError,setFetchError]=useState<Record<string,string>>({});
 useEffect(()=>{const stored=loadVoiceConfigs();const loaded=normalizeVoiceConfigs(stored);if(loaded.length>0){setConfigs(loaded);if(loaded.length!==stored.length)saveVoiceConfigs(loaded);}else{setConfigs(DEFAULT_VOICE_CONFIGS);saveVoiceConfigs(DEFAULT_VOICE_CONFIGS);}setIsLoaded(true);},[]);
 const persist=useCallback((next:VoiceApiConfig[])=>{setConfigs(next);saveVoiceConfigs(next)},[]);
 const addConfig=useCallback(()=>{const c:VoiceApiConfig={id:`voice-${Date.now()}`,name:"新语音配置",provider:"Minimax",apiKey:"",baseUrl:DEFAULT_MINIMAX_BASE_URL,region:"",model:"speech-2.8-turbo",defaultVoice:"male-qn-qingse",speechSpeed:DEFAULT_SPEECH_SPEED,enableSTT:true,enableTTS:true};persist([...configs,c]);setIsNewConfig(true);setEditingId(c.id)},[configs,persist]);
 useEffect(()=>{setSubpageRightAction("voice",<button onClick={addConfig} className="inline-flex h-10 items-center justify-center gap-1.5 whitespace-nowrap rounded-[20px] bg-black px-4 text-xs font-bold text-white shadow-sm transition-all hover:bg-gray-800 hover:shadow-md active:scale-95 focus:outline-none"><Plus size={15} strokeWidth={1.8}/><span>新增语音方案</span></button>);return()=>setSubpageRightAction("voice",null)},[addConfig,setSubpageRightAction]);
 const updateConfig=(id:string,updates:Partial<VoiceApiConfig>)=>persist(configs.map(c=>c.id===id?{...c,...updates}:c));
 const updateProvider=(id:string,p:string)=>{const c=configs.find(x=>x.id===id);if(p==="OpenAI"){updateConfig(id,{provider:"OpenAI",baseUrl:"https://api.openai.com/v1",model:"tts-1",defaultVoice:"alloy"});setManualModelIds(x=>({...x,[id]:true}));setManualVoiceIds(x=>({...x,[id]:false}));return;}if(p==="ElevenLabs"){updateConfig(id,{provider:"ElevenLabs",baseUrl:"https://api.elevenlabs.io/v1",model:c?.provider==="ElevenLabs"?(c.model||DEFAULT_ELEVENLABS_MODEL):DEFAULT_ELEVENLABS_MODEL,defaultVoice:c?.provider==="ElevenLabs"?(c.defaultVoice||""):"",speechSpeed:c?.provider==="ElevenLabs"?(c.speechSpeed??1):1,elevenLabsStability:c?.provider==="ElevenLabs"?(c.elevenLabsStability??DEFAULT_ELEVENLABS_STABILITY):DEFAULT_ELEVENLABS_STABILITY,elevenLabsSimilarity:c?.provider==="ElevenLabs"?(c.elevenLabsSimilarity??DEFAULT_ELEVENLABS_SIMILARITY):DEFAULT_ELEVENLABS_SIMILARITY,elevenLabsStyle:c?.provider==="ElevenLabs"?(c.elevenLabsStyle??DEFAULT_ELEVENLABS_STYLE):DEFAULT_ELEVENLABS_STYLE,elevenLabsSpeakerBoost:c?.provider==="ElevenLabs"?(c.elevenLabsSpeakerBoost??DEFAULT_ELEVENLABS_SPEAKER_BOOST):DEFAULT_ELEVENLABS_SPEAKER_BOOST});setManualModelIds(x=>({...x,[id]:false}));setManualVoiceIds(x=>({...x,[id]:true}));return;}if(p==="Inworld"){updateConfig(id,{provider:"Inworld",baseUrl:c?.provider==="Inworld"?(c.baseUrl||DEFAULT_INWORLD_BASE_URL):DEFAULT_INWORLD_BASE_URL,model:c?.provider==="Inworld"?(c.model||DEFAULT_INWORLD_TTS_MODEL):DEFAULT_INWORLD_TTS_MODEL,defaultVoice:c?.provider==="Inworld"?(c.defaultVoice||""):"",speechSpeed:c?.provider==="Inworld"?(c.speechSpeed??1):1});setManualModelIds(x=>({...x,[id]:false}));setManualVoiceIds(x=>({...x,[id]:true}));return;}if(p==="F5-TTS"){updateConfig(id,{provider:"F5-TTS",apiKey:"",baseUrl:c?.provider==="F5-TTS"?(c.baseUrl||DEFAULT_F5_TTS_BASE_URL):DEFAULT_F5_TTS_BASE_URL,model:c?.provider==="F5-TTS"?(c.model||DEFAULT_F5_TTS_MODEL):DEFAULT_F5_TTS_MODEL,defaultVoice:c?.provider==="F5-TTS"?(c.defaultVoice||""):"",f5RefAudio:c?.provider==="F5-TTS"?(c.f5RefAudio||""):"",f5RefText:c?.provider==="F5-TTS"?(c.f5RefText||""):"",f5NfeStep:c?.provider==="F5-TTS"?(c.f5NfeStep??DEFAULT_F5_TTS_NFE_STEP):DEFAULT_F5_TTS_NFE_STEP,f5RemoveSilence:c?.provider==="F5-TTS"?(c.f5RemoveSilence??false):false,speechSpeed:c?.provider==="F5-TTS"?(c.speechSpeed??1):1});setManualModelIds(x=>({...x,[id]:false}));setManualVoiceIds(x=>({...x,[id]:true}));return;}const mini=c?.provider==="Minimax";updateConfig(id,{provider:"Minimax",baseUrl:p==="MinimaxGlobal"?GLOBAL_MINIMAX_BASE_URL:DEFAULT_MINIMAX_BASE_URL,model:mini?(c?.model||"speech-2.8-turbo"):"speech-2.8-turbo",defaultVoice:mini?(c?.defaultVoice||"male-qn-qingse"):"male-qn-qingse",speechSpeed:mini?(c?.speechSpeed??1):1});if(!mini){setManualModelIds(x=>({...x,[id]:false}));setManualVoiceIds(x=>({...x,[id]:false}));}};
 const removeConfig=(id:string)=>{persist(configs.filter(c=>c.id!==id));setFetchedVoices(x=>{const n={...x};delete n[id];return n});setFetchError(x=>{const n={...x};delete n[id];return n});setManualModelIds(x=>{const n={...x};delete n[id];return n});setManualVoiceIds(x=>{const n={...x};delete n[id];return n});};
 const openCloneModal=(c:VoiceApiConfig)=>{setCloneTargetId(c.id);setCloneVoiceId(makeCloneVoiceId(c));setCloneFile(null);setCloneError("");setIsCloning(false)}; const closeCloneModal=()=>{if(isCloning)return;setCloneTargetId(null);setCloneVoiceId("");setCloneFile(null);setCloneError("")};
 const submitClone=async()=>{const c=configs.find(x=>x.id===cloneTargetId);if(!c)return;setCloneError("");const voiceId=cloneVoiceId.trim();if(!c.apiKey.trim()){setCloneError("请先填写 Minimax API Key");return}if(!voiceId||!/^[A-Za-z0-9_-]{4,64}$/.test(voiceId)){setCloneError("Voice ID 只能包含英文、数字、下划线和连字符，长度 4-64");return}if(!cloneFile){setCloneError("请上传一段音频文件");return}if(cloneFile.size>20*1024*1024){setCloneError("音频文件超过 20MB,请压缩后再试(30 秒左右的干净人声即可)");return}setIsCloning(true);try{const base=(c.baseUrl||DEFAULT_MINIMAX_BASE_URL).replace(/\/$/,"");const auth={Authorization:`Bearer ${c.apiKey.trim()}`};const parse=(t:string)=>{try{return JSON.parse(t) as Record<string,unknown>}catch{return null}};const err=(p:Record<string,unknown>|null)=>{const b=(p?.base_resp??{}) as Record<string,unknown>;const code=b.status_code??p?.status_code;return code&&String(code)!=="0"?String(b.status_msg||p?.status_msg||code):null};const f=new FormData();f.set("purpose","voice_clone");f.set("file",cloneFile,cloneFile.name||"voice-sample.mp3");const u=await fetch(`${base}/files/upload`,{method:"POST",headers:auth,body:f});const ut=await u.text(),ud=parse(ut),ue=err(ud);if(!u.ok||ue)throw new Error(ue||`样本上传失败 (HTTP ${u.status}) ${ut.slice(0,200)}`);const fr=(ud?.file??{}) as Record<string,unknown>,fid=fr.file_id??ud?.file_id??ud?.id;if(fid===undefined||fid===null||fid==="")throw new Error(`上传结果里没有 file_id: ${ut.slice(0,200)}`);const cr=await fetch(`${base}/voice_clone`,{method:"POST",headers:{...auth,"Content-Type":"application/json"},body:JSON.stringify({file_id:fid,voice_id:voiceId})}),ct=await cr.text(),cd=parse(ct),ce=err(cd);if(!cr.ok||ce)throw new Error(ce||`克隆失败 (HTTP ${cr.status}) ${ct.slice(0,200)}`);const v:VoiceOption={id:voiceId,name:`克隆音色 (${voiceId})`,createdAt:Date.now()};updateConfig(c.id,{defaultVoice:voiceId,customVoices:[...(c.customVoices||[]).filter(x=>x.id!==voiceId),v]});setFetchedVoices(x=>({...x,[c.id]:uniqueOptions([...(x[c.id]||[]),v])}));setManualVoiceIds(x=>({...x,[c.id]:false}));closeCloneModal()}catch(e){setCloneError(e instanceof Error?e.message:"克隆失败，请稍后重试")}finally{setIsCloning(false)}};
 const fetchVoices=async(c:VoiceApiConfig)=>{if(!c.apiKey.trim()){setFetchError(x=>({...x,[c.id]:`${c.provider} API Key 未配置`}));return}setIsFetching(x=>({...x,[c.id]:true}));setFetchError(x=>({...x,[c.id]:""}));try{if(c.provider==="Minimax"){const b=(c.baseUrl||DEFAULT_MINIMAX_BASE_URL).replace(/\/$/,"");const r=await fetch(`${b}/voice/clone`,{headers:{Authorization:`Bearer ${c.apiKey.trim()}`}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json(),raw=Array.isArray(d?.voices)?d.voices:Array.isArray(d?.data)?d.data:[],vs=raw.map((v:any)=>({id:String(v.voice_id||v.id||""),name:String(v.name||v.voice_name||v.voice_id||v.id||""),createdAt:typeof v.created_at==="number"?v.created_at:undefined})).filter((v:VoiceOption)=>v.id);setFetchedVoices(x=>({...x,[c.id]:uniqueOptions(vs)}));}else if(c.provider==="OpenAI"){setFetchedVoices(x=>({...x,[c.id]:DEFAULT_OPENAI_VOICES}))}else throw new Error("该服务商暂不支持拉取模型列表")}catch(e){setFetchError(x=>({...x,[c.id]:e instanceof Error?e.message:"同步失败"}))}finally{setIsFetching(x=>({...x,[c.id]:false}))}};
 const togglePreview=async(c:VoiceApiConfig)=>{if(playingVoiceId===c.id){audioRef.current?.pause();if(audioRef.current)audioRef.current.currentTime=0;setPlayingVoiceId(null);return}if(!c.apiKey.trim()){setFetchError(x=>({...x,[c.id]:`${c.provider} API Key 未配置`}));return}if(!c.defaultVoice.trim()){setFetchError(x=>({...x,[c.id]:c.provider==="F5-TTS"?"请先填写 F5-TTS 参考音频路径":c.provider==="ElevenLabs"?"请先填写 ElevenLabs Voice ID":c.provider==="Inworld"?"请先填写 Inworld Voice ID":"请先选择默认音色"}));return}setPlayingVoiceId(c.id);setFetchError(x=>({...x,[c.id]:""}));try{const text=c.provider==="Minimax"&&c.languageBoost?MINIMAX_PREVIEW_TEXT[c.languageBoost]||"你好，很高兴认识你。这是一段语音试听。":c.provider==="ElevenLabs"?"你好，很高兴认识你。这是一段 ElevenLabs 语音试听。":c.provider==="Inworld"?"你好，很高兴认识你。这是一段 Inworld AI 语音试听。":"你好，我现在是"+(c.defaultVoice||"默认")+"音色。很高兴认识你。",blob=await synthesizeSpeech(text,c);if(!blob)throw new Error("语音生成失败");const url=URL.createObjectURL(blob);if(audioRef.current){audioRef.current.pause();URL.revokeObjectURL(audioRef.current.src)}const a=new Audio(url);audioRef.current=a;a.onended=()=>{setPlayingVoiceId(null);URL.revokeObjectURL(url)};a.onerror=()=>{setPlayingVoiceId(null);setFetchError(x=>({...x,[c.id]:"试听音频播放失败"}));URL.revokeObjectURL(url)};await a.play()}catch(e){setPlayingVoiceId(null);setFetchError(x=>({...x,[c.id]:e instanceof Error?e.message:"试听失败"}))}};
 useEffect(()=>()=>{audioRef.current?.pause();if(audioRef.current?.src)URL.revokeObjectURL(audioRef.current.src)},[]); if(!isLoaded)return null;
 return <div className="flex flex-col gap-5 px-4 pb-8">{configs.length===0?<div className="rounded-2xl border border-dashed border-gray-300 px-5 py-10 text-center"><div className="text-sm font-semibold text-gray-800">暂无语音配置</div><div className="mt-1 text-xs text-gray-500">点击右上角“新增语音方案”开始配置。</div></div>:<div className="flex flex-col gap-3">{configs.map(c=><div key={c.id} className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-black/5"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-semibold text-gray-900">{c.name||"未命名语音"}</div><div className="mt-1 text-xs text-gray-500">{c.provider==="F5-TTS"?"F5-TTS 本机":c.provider==="ElevenLabs"?"ElevenLabs":c.provider==="Inworld"?"Inworld AI":c.provider==="OpenAI"?"OpenAI TTS":c.baseUrl===GLOBAL_MINIMAX_BASE_URL?"Minimax 海外版":"Minimax 国内版"}{c.model?` · ${c.model}`:""}</div></div><div className="flex items-center gap-1"><button onClick={()=>{setIsNewConfig(false);setEditingId(c.id)}} className="ui-link-btn" aria-label="编辑"><FileEdit size={18}/></button><button onClick={()=>{setConfirmDeleteId(c.id)}} className="ui-link-btn" data-variant="danger"><Trash2 size={18}/></button></div></div></div>)}</div>}
 {editingId&&<div className="modal-overlay modal-overlay-bottom"><div className="modal-sheet"><div className="modal-header"><button onClick={()=>{if(isNewConfig)removeConfig(editingId);setIsNewConfig(false);setEditingId(null)}} className="modal-header-btn modal-header-btn-muted"><X size={18}/></button><span className="modal-header-title">{isNewConfig?"添加语音配置":"编辑语音配置"}</span><button onClick={()=>{setIsNewConfig(false);setEditingId(null)}} className="modal-header-btn modal-header-btn-action"><Check size={18}/></button></div><div className="modal-body hide-scrollbar pb-10">{(()=>{const c=configs.find(x=>x.id===editingId);if(!c)return null;return <div className="flex flex-col gap-4"><div className="flex flex-col gap-1"><label className="menu-desc ml-1">配置名称 (Name)</label><Input type="text" value={c.name||""} onChange={e=>updateConfig(c.id,{name:e.target.value})} placeholder="例如: 我的语音助手"/></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">服务商 (Provider)</label><select value={providerSelectValue(c)} onChange={e=>updateProvider(c.id,e.target.value)} className="ui-select">{VOICE_PROVIDER_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>{c.provider!=="F5-TTS"&&<div className="flex flex-col gap-1"><label className="menu-desc ml-1">API Key</label><Input type="password" value={c.apiKey} onChange={e=>updateConfig(c.id,{apiKey:e.target.value})} placeholder="输入密钥..."/></div>}
 {c.provider==="OpenAI"&&<><div className="flex flex-col gap-1"><label className="menu-desc ml-1">接口地址 (Base URL)</label><Input value={c.baseUrl||""} onChange={e=>updateConfig(c.id,{baseUrl:e.target.value})} placeholder="https://api.openai.com/v1"/></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">语音模型 (TTS Model)</label><Input value={c.model||""} onChange={e=>updateConfig(c.id,{model:e.target.value})} placeholder="tts-1"/></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">识别模型 (STT Model)</label><Input value={c.sttModel||""} onChange={e=>updateConfig(c.id,{sttModel:e.target.value})} placeholder="whisper-1（留空使用默认）"/></div></>}
 {c.provider==="F5-TTS"&&<><div className="flex flex-col gap-1"><label className="menu-desc ml-1">本机 Bridge 地址</label><Input value={c.baseUrl||DEFAULT_F5_TTS_BASE_URL} onChange={e=>updateConfig(c.id,{baseUrl:e.target.value})} placeholder="http://127.0.0.1:7861"/></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">F5-TTS 模型</label><Input value={c.model||DEFAULT_F5_TTS_MODEL} onChange={e=>updateConfig(c.id,{model:e.target.value})}/></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">参考音频路径</label><Input value={c.f5RefAudio||""} onChange={e=>updateConfig(c.id,{f5RefAudio:e.target.value,defaultVoice:e.target.value})}/></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">参考音频文字（Reference Text）</label><textarea value={c.f5RefText||""} onChange={e=>updateConfig(c.id,{f5RefText:e.target.value})} className="ui-textarea min-h-[90px]"/></div></>}
 {c.provider==="ElevenLabs"&&<><div className="flex flex-col gap-1"><label className="menu-desc ml-1">语音模型 (TTS Model)</label><select value={ELEVENLABS_MODELS.some(m=>m.id===c.model)?c.model:DEFAULT_ELEVENLABS_MODEL} onChange={e=>updateConfig(c.id,{model:e.target.value})} className="ui-select">{ELEVENLABS_MODELS.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">朗读语言 (Language)</label><select value={c.languageBoost||""} onChange={e=>updateConfig(c.id,{languageBoost:e.target.value||undefined})} className="ui-select">{ELEVENLABS_LANGUAGE_OPTIONS.map(o=><option key={o.value||"auto"} value={o.value}>{o.label}</option>)}</select></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">语速 (Speed)</label><input type="range" min={ELEVENLABS_SPEED_MIN} max={ELEVENLABS_SPEED_MAX} step={ELEVENLABS_SPEED_STEP} value={c.speechSpeed??1} onChange={e=>updateConfig(c.id,{speechSpeed:Number(e.target.value)})} className="w-full accent-black"/></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">稳定度 / 相似度 / 风格</label><div className="text-xs text-gray-500">{(c.elevenLabsStability??DEFAULT_ELEVENLABS_STABILITY).toFixed(2)} / {(c.elevenLabsSimilarity??DEFAULT_ELEVENLABS_SIMILARITY).toFixed(2)} / {(c.elevenLabsStyle??DEFAULT_ELEVENLABS_STYLE).toFixed(2)}</div></div><div className="ui-toggle-row"><span className="menu-label font-medium">Speaker Boost</span><Toggle checked={c.elevenLabsSpeakerBoost??DEFAULT_ELEVENLABS_SPEAKER_BOOST} onChange={v=>updateConfig(c.id,{elevenLabsSpeakerBoost:v})}/></div></>}
 {c.provider==="Inworld"&&<div className="flex flex-col gap-1"><label className="menu-desc ml-1">语音模型 (TTS Model)</label><select value={INWORLD_TTS_MODELS.some(m=>m.id===c.model)?c.model:DEFAULT_INWORLD_TTS_MODEL} onChange={e=>updateConfig(c.id,{model:e.target.value})} className="ui-select">{INWORLD_TTS_MODELS.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><span className="menu-desc ml-1">Flash 适合实时聊天；TTS-2 适合更高品质。</span></div>}
 {c.provider==="Minimax"&&<><div className="flex flex-col gap-1"><label className="menu-desc ml-1">语速 (Speed)</label><input type="range" min={MINIMAX_SPEED_MIN} max={MINIMAX_SPEED_MAX} step={MINIMAX_SPEED_STEP} value={c.speechSpeed??1} onChange={e=>updateConfig(c.id,{speechSpeed:Number(e.target.value)})} className="w-full accent-black"/></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">音调 (Pitch)</label><input type="range" min={MINIMAX_PITCH_MIN} max={MINIMAX_PITCH_MAX} step={MINIMAX_PITCH_STEP} value={c.speechPitch??0} onChange={e=>updateConfig(c.id,{speechPitch:Number(e.target.value)})} className="w-full accent-black"/></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">朗读语言</label><select value={c.languageBoost||""} onChange={e=>updateConfig(c.id,{languageBoost:e.target.value||undefined})} className="ui-select">{MINIMAX_LANGUAGE_OPTIONS.map(o=><option key={o.value||"default"} value={o.value}>{o.label}</option>)}</select></div><div className="flex flex-col gap-1"><label className="menu-desc ml-1">语音模型 (TTS Model)</label><select value={DEFAULT_MINIMAX_MODELS.some(m=>m.id===c.model)?c.model:"__manual__"} onChange={e=>e.target.value!=="__manual__"&&updateConfig(c.id,{model:e.target.value})} className="ui-select">{DEFAULT_MINIMAX_MODELS.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}<option value="__manual__">手动输入...</option></select></div></>}
 <div className={c.provider==="F5-TTS"?"hidden":"flex flex-col gap-1"}><label className="menu-desc ml-1">{c.provider==="ElevenLabs"||c.provider==="Inworld"?"Voice ID":"默认音色 (Default Voice) 或 自定义 Voice ID"}</label><div className="flex gap-2">{manualVoiceIds[c.id]?<><Input value={c.defaultVoice} onChange={e=>updateConfig(c.id,{defaultVoice:e.target.value})} placeholder={c.provider==="OpenAI"?"alloy":c.provider==="ElevenLabs"?"例如 21m00Tcm4TlvDq8ikWAM":c.provider==="Inworld"?"粘贴 Inworld 克隆后的 Voice ID":"male-qn-qingse 或克隆 Voice ID"} className="flex-1"/><button type="button" onClick={()=>setManualVoiceIds(x=>({...x,[c.id]:false}))} className="ui-icon-btn"><List size={20}/></button></>:<select value={voiceOptionsForConfig(c,fetchedVoices).some(v=>v.id===c.defaultVoice)?c.defaultVoice:"__manual__"} onChange={e=>e.target.value==="__manual__"?setManualVoiceIds(x=>({...x,[c.id]:true})):updateConfig(c.id,{defaultVoice:e.target.value})} className="ui-select flex-1">{voiceOptionsForConfig(c,fetchedVoices).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}<option value="__manual__">手动输入...</option></select>}<button onClick={()=>togglePreview(c)} className="ui-icon-btn" data-active={playingVoiceId===c.id}>{playingVoiceId===c.id?<Pause size={20}/>:<Play size={20}/>}</button></div><div className="flex gap-2 mt-0.5">{!["ElevenLabs","Inworld"].includes(c.provider)&&<button onClick={()=>fetchVoices(c)} disabled={isFetching[c.id]} className="ui-btn ui-btn-soft-action w-full"><RefreshCw size={16}/>{isFetching[c.id]?"同步中...":c.provider==="Minimax"?"同步音色列表":"显示默认音色"}</button>}{c.provider==="Minimax"&&<button onClick={()=>openCloneModal(c)} disabled={!c.apiKey.trim()} className="ui-btn ui-btn-soft-action w-full"><Upload size={16}/>上传音频克隆音色</button>}</div>{fetchError[c.id]&&<Alert variant="danger"><AlertCircle size={14}/>{fetchError[c.id]}</Alert>}</div>
 <div className="ui-toggle-row"><span className="menu-label font-medium">启用语音合成 (TTS)</span><Toggle checked={c.enableTTS} onChange={v=>updateConfig(c.id,{enableTTS:v})}/></div>
 </div>})() }</div></div></div>}
 {cloneTargetId&&<div/>}{confirmDeleteId&&<ConfirmDialog title="确认删除？" message="删除配置后无法恢复。是否继续？" icon={AlertCircle} variant="danger" confirmLabel="确认删除" cancelLabel="取消" onConfirm={()=>{removeConfig(confirmDeleteId);setConfirmDeleteId(null)}} onCancel={()=>setConfirmDeleteId(null)}/>}</div>;
}
